-- Jordan Task Manager v1 Cloud Sync Edition
-- Chạy file này trong Supabase SQL Editor.

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  account_id text unique not null,
  name text default '-',
  platform text default 'mixed',
  status text default 'Live',
  proxy text default '',
  note text default '',
  selected boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  video_id text unique not null,
  name text default '',
  path text default '',
  folder text default '',
  size_bytes bigint default 0,
  status text default 'ready',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.proxies (
  id bigint generated by default as identity primary key,
  proxy_id text unique not null,
  proxy text default '',
  note text default '',
  status text default 'unchecked',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  post_id text unique not null,
  account_id text default '',
  video_id text default '',
  platform text default 'tiktok',
  caption text default '',
  status text default 'draft',
  scheduled_at timestamptz null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.post_logs (
  id bigint generated by default as identity primary key,
  post_id text default '',
  account_id text default '',
  platform text default '',
  action text default '',
  message text default '',
  created_at timestamptz default now()
);

create table if not exists public.hashtags (
  id bigint generated by default as identity primary key,
  tag_id text unique not null,
  platform text default 'mixed',
  tag text default '',
  note text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.settings (
  key text primary key,
  value jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.sync_logs (
  id bigint generated by default as identity primary key,
  source text default 'desktop_app',
  action text default '',
  message text default '',
  created_at timestamptz default now()
);

-- Demo row để Test Connection không lỗi khi bảng rỗng.
insert into public.settings (key, value)
values ('app', '{"name":"Jordan Task Manager","edition":"v1 Cloud Sync"}')
on conflict (key) do update set value = excluded.value, updated_at = now();

-- Free/simple mode:
-- Để app desktop dùng anon key đọc/ghi, có thể tạm tắt RLS trong giai đoạn test.
-- Khi dùng thật/team nhiều người, nên bật RLS + Auth theo project riêng.
alter table public.accounts disable row level security;
alter table public.videos disable row level security;
alter table public.proxies disable row level security;
alter table public.posts disable row level security;
alter table public.post_logs disable row level security;
alter table public.hashtags disable row level security;
alter table public.settings disable row level security;
alter table public.sync_logs disable row level security;


-- JTM v9.2 Auth & Roles
create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  user_id text unique not null,
  email text unique not null,
  display_name text default '',
  role text default 'member' check (role in ('admin','member')),
  status text default 'active' check (status in ('active','disabled')),
  password_salt text not null,
  password_hash text not null,
  last_login_at timestamptz null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.auth_logs (
  id bigint generated by default as identity primary key,
  log_id text unique not null,
  action text default '',
  user_email text default '',
  role text default '',
  message text default '',
  created_at timestamptz default now()
);

alter table public.app_users disable row level security;
alter table public.auth_logs disable row level security;
